services:
  api:
    image: api
    container_name: api-dev
    hostname: api
    networks:
      - my_network
    ports:
      - 8081:
      - 2000:2000
  front:
    image: front 
    container_name: front-dev
    hostname: front
    networks:
      - my_network
    ports:
      - 8080:80
  webservise:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - 8082:80
    depends_on:
      - db
    # volumes:
    #   - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: DockerMe
      WORDPRESS_DB_NAME: DockerMe
      WORDPRESS_DB_PASSWORD: sdfascsdvsfdvweliuoiquowecefcwaefef
    networks:
      - my_network
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: sdfascsdvsfdvweliuoiquowecefcwaefef
      MYSQL_DATABASE: DockerMe
      MYSQL_USER: DockerMe
      MYSQL_PASSWORD: sdfascsdvsfdvweliuoiquowecefcwaefef
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 80:80
networks:
  my_network:
    driver: bridge
volumes:
  db_data:
  wp_data:
